tasks:
  - name: install google-cloud-sdk & gcloud configs
    init: |
      curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-393.0.0-linux-x86_64.tar.gz
      tar -xvf google-cloud-cli-393.0.0-linux-x86_64.tar.gz
      ./google-cloud-sdk/install.sh
      rm google-cloud-cli-393.0.0-linux-x86_64.tar.gz
      pip install google-cloud-bigquery
      pip install pandas
      pip install pyarrow
      source ~/.bashrc # exec bash
      gcloud auth login --no-launch-browser
      read -p "Enter Your GCP Project ID: " GCP_ID
      gcloud auth application-default login --no-launch-browser
      gp sync-done gc-sdk
    command: |
      date -d "2020/1/1 1:23" +%s
      # bq cp --project_id=<prj> --location='asia-northeast1' <dataset>.<table>@1585767600000
      # bq show --project_id=<prj> --schema --format=prettyjson <dataset>.<table> > schema.json
      # BQコマンドでプロジェクト超えたコピー
      # bq cp sushi:original.m_mst_store sandbox:sample.m_mst_store
      # GCSのバケットをプロジェクト超えてコピー
      # https://1e100.4watcher365.dev/google-cloud/google-cloud-platform/cloud-storage-transfer-another-project/
  - name: new shell
    init: |
      gp sync-await gc-sdk
      pip install -r requirements.txt
      # MeCab 
      sudo apt-get install libmecab2 libmecab-dev mecab mecab-ipadic mecab-ipadic-utf8 mecab-utils
      
      jupyter notebook --generate-config
      echo -e '\nc.NotebookApp.contents_manager_class = "jupytext.TextFileContentsManager"' >> ~/.jupyter/jupyter_notebook_config.py
      echo -e '\nc.ContentsManager.default_jupytext_formats = "ipynb,py"' >> ~/.jupyter/jupyter_notebook_config.py
      jupyter notebook --ip=*
    openMode: split-right
vscode:
  extensions:
    - timonwong.shellcheck
  
