tasks:
  - name: install google-cloud-sdk & gcloud configs
    init: |
      curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-358.0.0-linux-x86_64.tar.gz
      tar -xvf google-cloud-sdk-358.0.0-linux-x86_64.tar.gz
      ./google-cloud-sdk/install.sh
      rm google-cloud-sdk-358.0.0-linux-x86_64.tar.gz
      pip install google-cloud-bigquery
      pip install pandas
      pip install pyarrow
      source ~/.bashrc
      gcloud auth login
      read -p "Enter Your GCP Project ID: " GCP_ID
      gcloud config set project $GCP_ID
      gcloud auth application-default login
      jupyter notebook --generate-config
      echo -e '\nc.NotebookApp.contents_manager_class = "jupytext.TextFileContentsManager"' >> ~/.jupyter/jupyter_notebook_config.py
      echo -e '\nc.ContentsManager.default_jupytext_formats = "ipynb,py"' >> ~/.jupyter/jupyter_notebook_config.py
      jupyter notebook --ip=*
      gp sync-done gc-sdk
  - name: new shell
    init: |
      gp sync-await gc-sdk
    openMode: split-right
vscode:
  extensions:
    - timonwong.shellcheck
  
